<?php

namespace App\Filament\Resources\Users\Tables;

use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;

class UsersTable
{
    public static function configure(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('legacy_id')
                    ->searchable(),
                TextColumn::make('line_id')
                    ->searchable(),
                TextColumn::make('apple_id')
                    ->searchable(),
                TextColumn::make('name')
                    ->searchable(),
                TextColumn::make('email')
                    ->label('Email address')
                    ->searchable(),
                TextColumn::make('email_verified_at')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('avatar_color')
                    ->searchable(),
                TextColumn::make('avatar_species')
                    ->searchable(),
                TextColumn::make('avatar_animal')
                    ->searchable(),
                TextColumn::make('daily_pet_count')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('last_pet_date')
                    ->date()
                    ->sortable(),
                TextColumn::make('last_gift_date')
                    ->date()
                    ->sortable(),
                TextColumn::make('equipped_outfit')
                    ->searchable(),
                TextColumn::make('height_cm')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('current_weight_kg')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('target_weight_kg')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('start_weight_kg')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('birth_date')
                    ->date()
                    ->sortable(),
                TextColumn::make('gender')
                    ->searchable(),
                TextColumn::make('activity_level')
                    ->searchable(),
                TextColumn::make('dietary_type')
                    ->searchable(),
                TextColumn::make('level')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('xp')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('current_streak')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('longest_streak')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('total_days')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('last_active_date')
                    ->date()
                    ->sortable(),
                TextColumn::make('subscription_tier')
                    ->searchable(),
                TextColumn::make('subscription_expires_at')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('daily_calorie_target')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('daily_protein_target_g')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('friendship')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('streak_shields')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('shield_last_refill')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('membership_tier')
                    ->searchable(),
                TextColumn::make('subscription_type')
                    ->searchable(),
                TextColumn::make('subscription_expires_at_iso')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('fp_ref_code')
                    ->searchable(),
                TextColumn::make('tier_verified_at')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('island_visits_used')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('island_visits_reset_at')
                    ->date()
                    ->sortable(),
                TextColumn::make('journey_cycle')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('journey_day')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('journey_last_advance_date')
                    ->date()
                    ->sortable(),
                TextColumn::make('journey_started_at')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('daily_water_goal_ml')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('onboarded_at')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('disclaimer_ack_at')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->recordActions([
                EditAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ]);
    }
}
